# Generated by Django 2.0 on 2017-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.CharField(default='title', max_length=32)),
                ('content', models.TextField(null=True)),
            ],
        ),
    ]
