# Generated by Django 2.0 on 2017-12-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171206_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='filename',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
