# Generated by Django 2.0 on 2017-12-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filename',
            field=models.CharField(default='', max_length=50),
        ),
    ]
