# Generated by Django 2.0 on 2017-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171208_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filename',
            field=models.ImageField(default=None, max_length=1000, null=True, upload_to=''),
        ),
    ]
