# Generated by Django 2.0 on 2017-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171208_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filename',
            field=models.FileField(default=None, max_length=50, null=True, upload_to='./blog/static/upload'),
        ),
    ]
