# Generated by Django 2.0 on 2017-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171209_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filename',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
